int ghost_scheduling_policy;
pthread_t ghost_sched_param_thread;
struct sched_param ghost_t1_sched_parameter;
int ghost_t1_scheduling_policy;
struct sched_param ghost_t2_sched_parameter;
int ghost_t2_scheduling_policy;
